### ISSUE TITLE
Request : Restore on Tears of kingdom

### ISSUE THREAD

**Issue by cualquiercosa327** [NiceneNerd/plasticity-rs#1]
Hello, I would love to know if this tool could be used to "port" content of breath of wild to Tears of Kingdom with their logic..

As example it would be awesome could port the wolf which appears if you scan the amibo of Zelda Twilight.

Or enemies as the Guardians.

I know the 3d model and animation can be done but no sure if their "behavior" (ai..)
Thanks

**Comment by NiceneNerd** [comment]
No. BOTW AI programs are specially structured AAMP files (`.aiprog`), where TOTK uses a new format for AI programs (`.ainb`) which has not yet been documented.
